services:
  database:
    image: postgres:15-alpine
    container_name: onmec_db
    environment:
      POSTGRES_DB: 'onmec'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - onmec_db_data:/var/lib/postgresql/data
    networks:
      - onmec_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    restart: unless-stopped

volumes:
  onmec_db_data:

networks:
  onmec_network:
    driver: bridge
