services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onmec_backend
    env_file:
      - ../.env.production.local
    ports:
      - '8083:8081'
    depends_on:
      - database
      - redis
    networks:
      - onmec_network
    volumes:
      - onmec_uploads:/app/uploads
    restart: unless-stopped

volumes:
  onmec_uploads:
  onmec_db_data:
  redis_data:

networks:
  onmec_network:
    driver: bridge
